version: '3.8'
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab6_nginx
    ports:
      - "8060:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - elasticsearch

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - elasticsearch
      - redis
      - clickhouse

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: lab6_clickhouse
    environment:
      - CLICKHOUSE_DB=products_db
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: lab6_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  redis_data:
  elastic_data:
  clickhouse_data: